# Generated by Django 4.2.2 on 2023-08-23 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('raffleshop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='brand',
        ),
    ]
