# Generated by Django 4.2.2 on 2023-08-27 14:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('raffleshop', '0002_remove_product_brand'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShoppingCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_address', models.TextField()),
                ('shopping_cart', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='raffleshop.shoppingcart')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checked_out', models.BooleanField(default=False)),
                ('raffle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='raffleshop.raffle')),
                ('shopping_cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='raffleshop.shoppingcart')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_type', models.CharField(choices=[('VIS', 'Visa'), ('MAS', 'MasterCard'), ('PAY', 'Payoneer')], default='VIS', max_length=3)),
                ('card_number', models.CharField(max_length=255)),
                ('name_on_card', models.CharField(max_length=255)),
                ('cvv', models.CharField(max_length=3)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_infos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
