# Generated by Django 4.2.2 on 2023-08-29 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raffleshop', '0005_remove_userprofile_delivery_address_deliveryaddress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentinfo',
            name='card_type',
            field=models.CharField(choices=[('VIS', 'Visa'), ('MAS', 'MasterCard'), ('PAY', 'Payoneer'), ('MAE', 'Maestro')], default='VIS', max_length=3),
        ),
    ]
